version: '3.8'

services:
  grok:
    image: ghcr.io/songdaopi/grok_chat_proxy:main
    container_name: grok_chat_proxy
    restart: unless-stopped
    ports:
      - "9898:9898"
    volumes:
      - ./config.json:/app/config.json
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - grok_net

networks:
  grok_net:
    driver: bridge
